#
1. GaussianNB
Best for continuous features (like in Iris: sepal length/width, petal length/width).

2. MultinomialNB
Designed for discrete counts (word frequencies in text classification, document-term matrix, etc.).

3. BernoulliNB
Works on binary features (0/1 yes/no type data).

# Import Libraries

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# GaussianNB

In [2]:
df = sns.load_dataset('iris')

X = df.drop('species' , axis=1)
y = df['species']
X_train , X_test, y_train , y_test  = train_test_split(X , y , test_size=0.2 , random_state=42)
model = GaussianNB()
model.fit(X_train , y_train)
y_pred = model.predict(X_test)
print("confusion matrix:\n" , confusion_matrix(y_test , y_pred))
print("Classification Report:\n" , classification_report(y_test , y_pred))


confusion matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# MultinomialNB

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# Sample SMS dataset
data = {
    "text": [
        "Win a free iPhone now!!!", 
        "Your account has been credited with $5000", 
        "Hello, are we meeting today?", 
        "Reminder: your bill is due tomorrow", 
        "Claim your lottery prize now!", 
        "Are you free for lunch?", 
        "Exclusive deal just for you", 
        "Hey, call me when you’re free", 
        "Congratulations! You won a gift card", 
        "Let’s catch up at 5"
    ],
    "label": ["spam", "spam", "ham", "ham", "spam", "ham", "spam", "ham", "spam", "ham"]
}
df = pd.DataFrame(data)

# Split features and labels
X = df['text']
y = df['label']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Convert text to word counts
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train MultinomialNB
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# Predictions
y_pred = model.predict(X_test_vec)

# Evaluation
print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


✅ Accuracy: 0.0

Confusion Matrix:
 [[0 1]
 [2 0]]

Classification Report:
               precision    recall  f1-score   support

         ham       0.00      0.00      0.00       1.0
        spam       0.00      0.00      0.00       2.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0

